- name: Check OS distribution Debian
  fail: msg="OS of {{inventory_hostname}} is not Debian"
  when: ansible_distribution != 'Debian'

- name: Check Debian major version 8 or 9
  fail: msg="OS of {{inventory_hostname}} is not Debian"
  when: ansible_distribution_major_version != '8' and ansible_distribution_major_version != '9'

- name: Load repositories list
  include_vars:
    file: vars/debian_{{ ansible_distribution_major_version }}_repos.yml

- name: Is PostgreSQL version defined
  fail: msg="postgresql_version var is not defined"
  when: postgresql_version is not defined

- name: Add package repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
  - "{{ apt_repos }}"

- name: "'apt-get update' if the last one is more than 300 seconds ago"
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Prevent auto stop/start/restart
  template:
    src: policy-rc.d
    dest: /usr/sbin/policy-rc.d
    backup: yes
    mode: '0755'
