Vagrant.configure("2") do |config|
  config.vm.define "pgsql_master" do |pgsql_master|
    pgsql_master.vm.box = "debian/jessie64"
    pgsql_master.vm.network "private_network", ip: "172.30.1.5"

    #copy public ssh key
    pgsql_master.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
      mkdir -p /root/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    pgsql_master.vm.provision :shell, :path => "postgresql-setup/bootstrap_master.sh"
  end

  config.vm.define "pgsql_standby" do |pgsql_standby|
    pgsql_standby.vm.box = "debian/jessie64"
    pgsql_standby.vm.network "private_network", ip: "172.30.1.6"

    #copy public ssh key
    pgsql_standby.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
      mkdir -p /root/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    pgsql_standby.vm.provision :shell, :path => "postgresql-setup/bootstrap_standby.sh"
  end
end