- name: Register master checkpoint location
  shell: '/usr/lib/postgresql/{{ postgresql_version }}/bin/pg_controldata /var/lib/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_names[0] }}/ | grep ''Latest checkpoint location'''
  become: yes
  become_user: '{{ postgres_service_user }}'
  register: master_checkpoint

### Handle standby02

- name: Wait until standby02 is synced
  shell: 'psql -qt -c "select pg_last_xlog_receive_location() = pg_last_xlog_replay_location()" | grep -q "t"'
  become: yes
  become_user: '{{ postgres_service_user }}'
  retries: 600 # 10 minutes
  delay: 1
  register: standby02_sync
  until: standby02_sync.rc == 0
  delegate_to: '{{ standby02_hostname }}'

- name: Stop standby02
  shell: 'pg_ctlcluster -m fast {{ postgresql_version }} {{ postgresql_cluster_names[0] }} stop'
  async: 600 # 10 minutes
  poll: 3
  delegate_to: '{{ standby02_hostname }}'

- name: Register standby02 checkpoint location
  shell: '/usr/lib/postgresql/{{ postgresql_version }}/bin/pg_controldata /var/lib/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_names[0] }}/ | grep ''Latest checkpoint location'''
  become: yes
  become_user: '{{ postgres_service_user }}'
  delegate_to: '{{ standby02_hostname }}'
  register: standby02_checkpoint

- name: Compare checkpoint location standby02
  fail:
    msg: standby02 checkpoint location is mismatch
  when: master_checkpoint.stdout != standby02_checkpoint.stdout
